#!/usr/bin/env python3
"""Generate the 4-bit atlas using only Python's standard library."""
import argparse
import re
import sys
sys.dont_write_bytecode = True
import importlib.util
from pathlib import Path
root = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location('masks', root / 'assets/ui/masks.py')
masks = importlib.util.module_from_spec(spec)
spec.loader.exec_module(masks)
# One 256x96 texture page, at VRAM word (640,0). Index zero is transparent;
# every other index is opaque, including the dark interiors of outlined notes.
PALETTE = [0, 0x16, 0x34, 0xe8, 0xf2, 0x9a, 0x4e, 0x60]
WIDTH, HEIGHT = 256, 96
pixels = [[0] * WIDTH for _ in range(HEIGHT)]
def ink(mask, x, y, color):
    for j, row in enumerate(mask.split('/')):
        for i, ch in enumerate(row):
            if ch == '#': pixels[y+j][x+i] = color

def label(s, x, y, color):
    for ch in s:
        ink(masks.TILE_FONT[ch], x, y, color)
        x += len(masks.TILE_FONT[ch].split('/')[0]) + 1

# 16x16 slots retain gutters even when sprites touch. Bodies are 13x14.
for kind in range(8):
    ox = kind * 16
    bright = kind in (0, 4, 5, 7)
    field = 3 if bright else 1 if kind == 1 else 2
    for y in range(1, 15):
        inset = 1 if y in (1,14) else 0
        for x in range(2+inset, 15-inset): pixels[y][ox+x] = field
    if kind == 1:
        for y in range(1,15):
            for x in range(2,15):
                if pixels[y][ox+x] and any(pixels[yy][ox+xx] == 0 for xx,yy in ((x-1,y),(x+1,y),(x,y-1),(x,y+1))):
                    pixels[y][ox+x] = 3
    if kind in (4,7): ink(masks.ICONS[4 if kind == 4 else 5], ox+4, 3, 1)
ink(masks.RELATIVE_MARK, 6*16+6, 9, 5)
# Pass-through marker, also one sprite rather than five separate pixels.
ink('#../##./###/##./#..', 128+7, 6, 5)
metrics = []
for code in range(32, 127):
    mask = masks.FONT.get(chr(code), masks.FONT['?'])
    i = code-32
    ink(mask, i%32*8, 24+i//32*8, 4)
    metrics.append(len(mask.split('/')[0])+1)

small_chars = '0123456789ABCDEFG+LR%h'
for i, ch in enumerate(small_chars):
    ink(masks.SMALL_FONT[ch], i*4, 48, 4)
    ink(masks.SMALL_FONT[ch], i*4, 56, 1)

# Preserve the original wordmark's 60-unit grid at one screen pixel per cell.
logo = (root / 'assets/ui/jacquard-logo.svg').read_text()
for x, y, w in re.findall(r'M(-?\d+) (-?\d+)h(\d+)v60h-\d+z', logo):
    x, y, w = (int(x)-60)//60, (int(y)+720)//60, int(w)//60
    for col in range(w): pixels[64+y][x+col] = 4

def generate(destination):
    packed = []
    for row in pixels:
        for x in range(0, WIDTH, 8):
            packed.append(sum(row[x+i] << (4*i) for i in range(8)))
    colors = [0] + [(v>>3)*0x421 for v in PALETTE[1:]] + [0]*8
    clut = [colors[i] | colors[i+1]<<16 for i in range(0,16,2)]
    def array(name, typ, values):
        return 'static const '+typ+' '+name+'[] = {\n'+''.join('    '+','.join(str(v) for v in values[i:i+8])+',\n' for i in range(0,len(values),8))+'};\n'
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text('// Generated by scripts/generate-assets.py; edit assets/ui/masks.py and jacquard-logo.svg.\n'+
        array('ui_pixels','uint32_t',packed)+array('ui_clut','uint32_t',clut)+array('ui_advance','uint8_t',metrics))
if __name__ == '__main__':
    p = argparse.ArgumentParser(); p.add_argument('output', type=Path)
    generate(p.parse_args().output)
