#!/usr/bin/env python3
"""Deterministic octave-root SPU ADPCM loops and tuning/error measurements."""
import math
import struct
import sys
from pathlib import Path

COEFFICIENTS = [(0, 0), (60, 0), (115, -52), (98, -55), (122, -60)]

def encode(pcm):
    history = [0, 0]
    data, decoded = bytearray(), []
    for offset in range(0, len(pcm), 28):
        best = None
        # Reset prediction at each loop entry. This makes every traversal and
        # a fresh key-on decode identically, including the first 28 samples.
        for predictor in ([0] if offset == 0 else range(5)):
            a, b = COEFFICIENTS[predictor]
            for shift in range(13):
                h1, h2 = history
                values, output, error = [], [], 0
                scale = 1 << (12-shift)
                for target in pcm[offset:offset+28]:
                    prediction = (h1*a+h2*b+32)//64
                    nibble = max(-8, min(7, round((target-prediction)/scale)))
                    sample = max(-32768, min(32767, prediction+nibble*scale))
                    values.append(nibble & 15)
                    output.append(sample)
                    error += (sample-target)**2
                    h2, h1 = h1, sample
                candidate = (error, predictor, shift, values, output, [h1, h2])
                if best is None or error < best[0]:
                    best = candidate
        _, predictor, shift, values, output, history = best
        flags = 4 if offset == 0 else 0
        if offset+28 == len(pcm):
            flags |= 3
        data.extend([predictor*16+shift, flags])
        data.extend(values[i] | values[i+1]*16 for i in range(0, 28, 2))
        decoded.extend(output)
    return data, decoded

def generate(path):
    data, roots, pitches, report = bytearray(), [], [], []
    for octave in range(10):
        length = [2688,1344,672,336,168,84,84,84,84,84][octave]
        cycles = 1 << max(0, octave-5)
        pcm = [round(16384*math.sin(2*math.pi*cycles*i/length)) for i in range(length)]
        encoded, decoded = encode(pcm)
        roots.append(len(data))
        data.extend(encoded)
        error = sum((a-b)**2 for a,b in zip(pcm, decoded))
        snr = 10*math.log10(sum(x*x for x in pcm)/error)
        report.append(f'C{octave}: {length} samples, {cycles} cycles, SNR {snr:.2f} dB, loop delta {decoded[0]-decoded[-1]}, ideal {pcm[0]-pcm[-1]}')
        for semitone in range(12 if octave<9 else 1):
            note = octave*12+semitone
            hz = 440*2**((note-57)/12)
            pitch = round(hz*length/cycles/44100*4096)
            actual = 44100*pitch/4096*cycles/length
            cents = 1200*math.log2(actual/hz)
            pitches.append(pitch)
            report.append(f'  {note}: pitch {pitch}, {actual:.6f} Hz, {cents:+.4f} cents')
    # SDK DMA transfers round to a 64-byte boundary. Pad explicitly rather
    # than letting SpuWrite read beyond the generated array.
    data.extend(bytes((-len(data)) % 64))
    def array(name, typ, values):
        return f'static const {typ} {name}[] = {{\n'+''.join('    '+','.join(str(x) for x in values[i:i+12])+',\n' for i in range(0,len(values),12))+'};\n'
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text('// Generated by scripts/generate-audio.py.\n'+array('sine_data','uint32_t',struct.unpack('<'+'I'*(len(data)//4),data))+array('sine_offsets','uint16_t',roots)+array('sine_pitch','uint16_t',pitches))
    path.with_suffix('.txt').write_text('\n'.join(report)+'\n')
    assert len(data) < 512*1024-0x1000
    assert all(0 < p < 0x4000 for p in pitches)

if __name__ == '__main__':
    generate(Path(sys.argv[1]))
